export const Config = {
  APP_API_URL: process.env.NEXT_PUBLIC_APP_API_URL || "http://localhost:3001",
  PINATA_GATEWAY: process.env.NEXT_PUBLIC_PINATA_GATEWAY,
  WEB3AUTH_CLIENT_ID: process.env.NEXT_PUBLIC_WEB3AUTH_CLIENT_ID,
  DISPERSE_ADDRESS: process.env.NEXT_PUBLIC_DISPERSE_ADDRESS,
  SEPOLIA_RPC_URL: process.env.NEXT_PUBLIC_SEPOLIA_RPC_URL,
  APP_SALT: "0dsfwsaf2na8mc80a8efv8qpo",
};
