export const ACCOUNT_OVERVIEW_UI = {
  dataSeller: {
    totalEarned: {
      icon1: "Coins",
      icon1Color: "text-blue-600",
      icon2: "TrendingUp",
      icon2Color: "text-green-600",
      title: "Total Earned",
      color: "from-blue-50 to-blue-100 border-blue-200",
    },
    nbDataPointsShared: {
      icon1: "Database",
      icon1Color: "text-teal-600",
      icon2: "Activity",
      icon2Color: "text-green-600",
      title: "Medical Files",
      color: "from-teal-50 to-teal-100 border-teal-200",
    },
    nbActiveStudies: {
      icon1: "BookOpenText",
      icon1Color: "text-purple-600",
      icon2: "RefreshCcw",
      icon2Color: "text-green-600",
      title: "Active Studies",
      color: "from-purple-50 to-purple-100 border-purple-200",
    },
    nbCompletedStudies: {
      icon1: "CheckCircle",
      icon1Color: "text-green-600",
      icon2: "CheckCircle",
      icon2Color: "text-green-600",
      title: "Completed Studies",
      color: "from-green-50 to-green-100 border-green-200",
    },
  },
  researcher: {
    totalSpent: {
      icon1: "TrendingUp",
      icon1Color: "text-orange-600",
      icon2: "DollarSign",
      icon2Color: "text-orange-600",
      title: "Total Spent",
      color: "from-orange-50 to-orange-100 border-orange-200",
    },
    nbParticipants: {
      icon1: "Users",
      icon1Color: "text-teal-600",
      icon2: "Activity",
      icon2Color: "text-green-600",
      title: "Participants Enrolled",
      color: "from-teal-50 to-teal-100 border-teal-200",
    },
    nbActiveStudies: {
      icon1: "BookOpenText",
      icon1Color: "text-purple-600",
      icon2: "RefreshCcw",
      icon2Color: "text-green-600",
      title: "Active Studies",
      color: "from-purple-50 to-purple-100 border-purple-200",
    },
    nbCompletedStudies: {
      icon1: "CheckCircle",
      icon1Color: "text-green-600",
      icon2: "CheckCircle",
      icon2Color: "text-green-600",
      title: "Completed Studies",
      color: "from-green-50 to-green-100 border-green-200",
    },
  },
};
