name: Backend Api CI

on:
  push:
    branches: [dev, main]
    paths:
      - "apps/api/**"
  pull_request:
    branches: [dev, main]
    paths:
      - "apps/api/**"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      IS_CI: "true"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --cwd apps/api

      - name: Lint
        run: bun run lint:api

      - name: Test
        run: bun run test:api

      - name: Build
        run: bun run --cwd apps/api build
