name: Deploy Web and API on Release

on:
  release:
    types: [published]
  push:
    branches:
      - chore/add-supabase-dependency

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cura-api:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cura-api:${{ github.event.release.tag_name || github.sha }}

      - name: Build and push Web Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/web
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cura-web:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cura-web:${{ github.event.release.tag_name || github.sha }}
          build-args: |
            NEXT_PUBLIC_APP_API_URL=${{ secrets.NEXT_PUBLIC_APP_API_URL }}
            NEXT_PUBLIC_APP_API_KEY=${{ secrets.NEXT_PUBLIC_APP_API_KEY }}
            NEXT_PUBLIC_LIGHTHOUSE_API_KEY=${{ secrets.NEXT_PUBLIC_LIGHTHOUSE_API_KEY }}
            NEXT_PUBLIC_WEB3AUTH_CLIENT_ID=${{ secrets.NEXT_PUBLIC_WEB3AUTH_CLIENT_ID }}

  trigger-render-redeploys:
    needs: build-and-push-images
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API Render Redeploy
        run: curl -X POST ${{ secrets.API_REDEPLOY_WEBHOOK_URL }}

      - name: Trigger Web Render Redeploy
        run: curl -X POST ${{ secrets.WEB_REDEPLOY_WEBHOOK_URL }}
