name: Deploy Web and API on Release

on:
  release:
    types: [published]
    # TODO: [LT] REMOVE, temporary for testing deployment
  push:
    branches: [chore/ci-cd-backend-initial-setup]

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cura-api:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cura-api:${{ github.event.release.tag_name || github.sha }}

      - name: Build and push Web Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/web
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cura-web:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cura-web:${{ github.event.release.tag_name || github.sha }}

  # deploy-web-to-vercel:
  #   needs: build-and-push-images
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger Vercel deployment
  #       run: |
  #         curl -X POST "https://api.vercel.com/v1/projects/${{ secrets.VERCEL_PROJECT_ID }}/deployments" \
  #           -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
  #           -H "Content-Type: application/json" \
  #           --data '{
  #             "name": "web",
  #             "target": "production",
  #             "image": "ghcr.io/${{ github.repository_owner }}/web:${{ github.event.release.tag_name }}"
  #           }'
