# TODO: [LT] Add front-end deployment (with Vercel)

name: Deploy

on:
  release:
    types: [published]

build-and-push-image:
  runs-on: ubuntu-latest
  environment: production
  steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push API Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./api
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/api:latest
          ghcr.io/${{ github.repository_owner }}/api:${{ github.event.release.tag_name }}

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./demo
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/frontend:latest
          ghcr.io/${{ github.repository_owner }}/frontend:${{ github.event.release.tag_name }}

deploy-api-to-railway:
  needs: build-and-push-image
  runs-on: ubuntu-latest
  environment: production
  steps:
    - uses: actions/checkout@v4
    - name: Install Railway CLI
      run: npm install -g @railway/cli
    - name: Deploy to Railway
      run: railway up --service api --image ghcr.io/${{ github.repository_owner }}/api:${{ github.event.release.tag_name }} --detach
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

deploy-frontedn-to-vercel:
  needs: build-and-push-frontend-image
  runs-on: ubuntu-latest
  environment: production
  steps:
    - name: Trigger Vercel deployment
      run: |
        curl -X POST "https://api.vercel.com/v1/projects/${{ secrets.VERCEL_PROJECT_ID }}/deployments" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{
            "name": "frontend",
            "target": "production",
            "image": "ghcr.io/${{ github.repository_owner }}/frontend:${{ github.event.release.tag_name }}"
          }'
